### ISSUE TITLE
linker error 

### ISSUE THREAD

**Issue by 4meta5** [shekohex/flutterust#1]
This my output when I run `cargo make`

```
➜  flutterust git:(master) cargo make     
[cargo-make] INFO - cargo make 0.30.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: workspace
[cargo-make][1] INFO - External file not found or is not a file, skipping.
[cargo-make][1] INFO - Project: adder-ffi
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: default
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Running Task: format
[cargo-make][1] INFO - Execute Command: "cargo" "fmt"
[cargo-make][1] INFO - Running Task: format-flow
[cargo-make][1] INFO - Running Task: pre-android
[cargo-make][1] INFO - Running Task: android-aarch64
[cargo-make][1] INFO - Execute Command: "cargo" "ndk" "--platform" "28" "--target" "aarch64-linux-android" "build"
   Compiling libc v0.2.69
   Compiling proc-macro2 v1.0.12
   Compiling unicode-xid v0.2.0
   Compiling cfg-if v0.1.10
   Compiling getrandom v0.1.14
   Compiling syn v1.0.18
   Compiling serde v1.0.106
   Compiling bitflags v1.2.1
   Compiling ppv-lite86 v0.2.6
   Compiling ryu v1.0.4
   Compiling log v0.4.8
   Compiling unicode-width v0.1.7
   Compiling ansi_term v0.11.0
   Compiling unicode-segmentation v1.6.0
   Compiling vec_map v0.8.1
   Compiling cbindgen v0.14.2
   Compiling itoa v0.4.5
   Compiling remove_dir_all v0.5.2
   Compiling strsim v0.8.0
   Compiling adder v0.1.0 (/Users/4meta5/flutter-bin/flutterust/native/adder)
   Compiling textwrap v0.11.0
   Compiling heck v0.3.1
   Compiling quote v1.0.4
   Compiling atty v0.2.14
   Compiling clap v2.33.0
   Compiling rand_core v0.5.1
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling tempfile v3.1.0
   Compiling serde_derive v1.0.106
   Compiling toml v0.5.6
   Compiling serde_json v1.0.52
   Compiling adder-ffi v0.1.0 (/Users/4meta5/flutter-bin/flutterust/native/adder-ffi)
error: linker `/Users/4meta5/Library/Android/sdk/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `adder-ffi`.

To learn more, run the command again with --verbose.
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

```

So I guess I need to configure/build/download that toolchain for the Android SDK.

Note: I followed the installation instructions and I did install the Rust compiler backend that the linker error specifies. I think the SDK doesn't have something it needs and that's what's throwing the error but I haven't been able to find installation instructions for Android SDK aarch64-linux-android28-clang with a quick search...

```
➜  flutterust git:(master) rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
info: component 'rust-std' for target 'armv7-linux-androideabi' is up to date
info: component 'rust-std' for target 'x86_64-linux-android' is up to date
info: component 'rust-std' for target 'i686-linux-android' is up to date
```

**Comment by 4meta5** [comment]
answer might be here https://developer.android.com/ndk/guides/standalone_toolchain

**Comment by shekohex** [comment]
Hi, this issue related that your `$ANDROID_NDK_HOME` pointing to the wrong place, you need first [install the Android NDK](https://developer.android.com/studio/projects/install-ndk) after that you should set the `$ANDROID_NDK_HOME` to the root of the NDK tools; In Mac, it looks something like this
```sh
export $ANDROID_NDK_HOME="/Users/$USER/Library/Android/sdk/ndk/21.1.6352462"
```
the `21.1.6352462` part of the path is the current version of NDK installed.

after that everything should work normally 😄

**Comment by 4meta5** [comment]
I set it in my zshrc file like

```
export ANDROID_NDK_HOME="/Users/4meta5/Library/Android/sdk/ndk/21.1.6352462"
```

and now my error is

```
   Compiling adder-ffi v0.1.0 (/Users/4meta5/flutter-bin/flutterust/native/adder-ffi)
error: linker `/Users/4meta5/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `adder-ffi`.

To learn more, run the command again with --verbose.
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

but I'm very sure that this is due to failed installation of some assumed Android NDK feature. It will be good when I figure out what it is because I just did a default installation so I'm sure others will need to do whatever it is I need to do...

I'll follow the instructions on that link to try to install the specific version for the Android NDK next. I'll close this issue once I've figured it out.

**Comment by 4meta5** [comment]
actually in the ios emulator, I'm getting this error now

    ```
    Errno::ENOENT - No such file or directory @ realpath_rec -
    /Users/shadykhalifa
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `reference_for_path'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :269:in `add_file_reference'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:223:in
    `block (2 levels) in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:222:in
    `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:222:in
    `block in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:213:in
    `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:213:in
    `add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:116:in
    `block in add_vendored_libraries'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:145:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:115:in
    `add_vendored_libraries'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:48:in
    `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator.rb:101:in `block in
    install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:145:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator.rb:99:in `install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/single_pods_project_generator.rb:17:in `generate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:308:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:303:in `create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:295:in `generate_pods_project'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:174:in `integrate'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/in
    stall.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:i
    n `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb
    :52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```

**Comment by 4meta5** [comment]
This is the current error I am getting when I run `cargo make ios`:
    ```
    Errno::ENOENT - No such file or directory @ realpath_rec -
    /Users/shadykhalifa
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `realpath'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :326:in `reference_for_path'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/project.rb
    :269:in `add_file_reference'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:223:in
    `block (2 levels) in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:222:in
    `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:222:in
    `block in add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:213:in
    `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:213:in
    `add_file_accessors_paths_to_pods_group'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:116:in
    `block in add_vendored_libraries'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:145:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:115:in
    `add_vendored_libraries'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator/file_references_installer.rb:48:in
    `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator.rb:101:in `block in
    install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:145:in `message'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/pods_project_generator.rb:99:in `install_file_references'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/
    xcode/single_pods_project_generator.rb:17:in `generate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:308:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_inter
    face.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:303:in `create_and_save_projects'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:295:in `generate_pods_project'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:174:in `integrate'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.
    rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/in
    stall.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:i
    n `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb
    :52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```
