### ISSUE TITLE
App Runtime Issue in windows 10 x64

### ISSUE THREAD

**Issue by arnabanimesh** [shekohex/flutterust#22]
## System Information

```
OS: Windows 10 X64 20H2 19042.867
Flutter 2.0.1
Dart 2.12.0
cargo-ndk: 0.2.0
Rust: 1.50.0
crate versions: as per master
Emulator: Pixel_3a_API_30_x86
```
SKIP THIS SECTION FOR ISSUES

---
## Initial cargo make output

```
[cargo-make] INFO - cargo make 0.32.14
[cargo-make] WARN - Found unknown key: tasks.?.build.mac.?.description in file: .\Makefile.toml
[cargo-make] WARN - Found unknown key: tasks.?.build.mac.?.category in file: .\Makefile.toml
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: clean
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: workspace

C:\Users\user\Downloads\flutterust>cd "C:\Users\user\Downloads\flutterust"

C:\Users\user\Downloads\flutterust>PUSHD native\adder-ffi

C:\Users\user\Downloads\flutterust\native\adder-ffi>cargo make --disable-check-for-updates --allow-private --no-on-error --loglevel=info --env CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER=adder-ffi --profile development -- clean
[cargo-make][1] WARN - Found unknown key: tasks.?.build.mac.?.description in file: \\?\C:\Users\user\Downloads\flutterust\Makefile.toml
[cargo-make][1] WARN - Found unknown key: tasks.?.build.mac.?.category in file: \\?\C:\Users\user\Downloads\flutterust\Makefile.toml
[cargo-make][1] INFO - Project: adder-ffi
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: clean
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Execute Command: "cargo" "clean"
[cargo-make][1] INFO - Build Done in 0.17 seconds.

C:\Users\user\Downloads\flutterust\native\adder-ffi>if 0 NEQ 0 exit /b 0

C:\Users\user\Downloads\flutterust\native\adder-ffi>POPD

C:\Users\user\Downloads\flutterust>PUSHD native\scrap-ffi

C:\Users\user\Downloads\flutterust\native\scrap-ffi>cargo make --disable-check-for-updates --allow-private --no-on-error --loglevel=info --env CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER=scrap-ffi --profile development -- clean
[cargo-make][1] WARN - Found unknown key: tasks.?.build.mac.?.description in file: \\?\C:\Users\user\Downloads\flutterust\Makefile.toml
[cargo-make][1] WARN - Found unknown key: tasks.?.build.mac.?.category in file: \\?\C:\Users\user\Downloads\flutterust\Makefile.toml
[cargo-make][1] INFO - Project: scrap-ffi
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: clean
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Execute Command: "cargo" "clean"
[cargo-make][1] INFO - Build Done in 0.16 seconds.
```

## Flutter run output

```
Running "flutter pub get" in flutterust...                          3.9s
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        95.2s
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                13.4s
Activating Dart DevTools...                                         4.8s
I/flutter ( 7547): Scrap Setup Done
Syncing files to device sdk gphone x86 arm...                      303ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 arm is available at: http://127.0.0.1:52410/bjwmWsqeVIk=/

Flutter DevTools, a Flutter debugger and profiler, on sdk gphone x86 arm is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A52410%2FbjwmWsqeVIk%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
```
---
# 1. Scraping Issue:

When clicking on the scrape button the following issue appears:

```
I/flutter ( 7547): invalid utf-8 sequence of 1 bytes from index 1
E/flutter ( 7547): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: invalid utf-8 sequence of 1 bytes from index 1
E/flutter ( 7547): #0      Scrap._throwError (package:scrap/scrap.dart:34:5)
E/flutter ( 7547): #1      Scrap.loadPage (package:scrap/scrap.dart:23:7)
E/flutter ( 7547): #2      _MyHomePageState._showWebPage (package:flutterust/main.dart:86:30)
E/flutter ( 7547): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
E/flutter ( 7547): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7547): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter ( 7547): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 7547): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter ( 7547): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7547): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter ( 7547): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter ( 7547): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter ( 7547): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter ( 7547): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter ( 7547): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
E/flutter ( 7547): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
E/flutter ( 7547): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter ( 7547): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
E/flutter ( 7547): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
E/flutter ( 7547): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
E/flutter ( 7547): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
E/flutter ( 7547): #21     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter ( 7547): #22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 7547): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter ( 7547): #24     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter ( 7547): #25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter ( 7547): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter ( 7547):
```

# 2. Counting issue:

When clicking on the <kbd>+</kbd> button it shows the following integers sequentially:

```
-1177495951
1897028546
676585747
-543857052
-1764299851
1310224646
89781847
```

**Note:** Running the apk from the releases section seem to work just fine.

**Comment by shekohex** [comment]
I guess maybe the issue from you use a new version of flutter? I see using flutter 2.0, which in my opinion would require FFI 1.0, which we do currently not support, yet!

But, aside from that, getting the increment FAB with the adder crate to not work properly does sound really weird!

I guess I should update the dart-bindgen to FFI 1.0 (https://github.com/sunshine-protocol/dart-bindgen/issues/7) and/or deprecate it and start using the official [ffigen](https://github.com/dart-lang/ffigen) provided by the dart team.

**Comment by arnabanimesh** [comment]
Installed flutter 1.22.6

```
Waiting for sdk gphone x86 arm to report its views...                7ms
D/HostConnection( 9503): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2
D/EGL_emulation( 9503): eglMakeCurrent: 0xf70e1aa0: ver 2 0 (tinfo 0xf741a130) (first time)
I/OpenGLRenderer( 9503): Davey! duration=1632ms; Flags=1, IntendedVsync=5800736534042, Vsync=5800736534042, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=5800741800300, AnimationStart=5800741822300, PerformTraversalsStart=5800741850900, DrawStart=5801449436900, SyncQueued=5801450696800, SyncStart=5801493522600, IssueDrawCommandsStart=5801494500800, SwapBuffers=5802380596200, FrameCompleted=5802411408300, DequeueBufferDuration=13855100, QueueBufferDuration=945800, GpuCompleted=72904454231491230,
I/Choreographer( 9503): Skipped 99 frames!  The application may be doing too much work on its main thread.
Syncing files to device sdk gphone x86 arm...                    1,391ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 arm is available at: http://127.0.0.1:61052/D3KPFNA64hY=/
I/flutter ( 9503): Scrap Setup Done
```

Scraping doesn't work and adder shows random numbers. No additional error outputs generated.

**Comment by arnabanimesh** [comment]
Maybe if you can share your setup. I will run using the same.
